
# Path to image for classify
img_path: script_test/gnil/gnil.jpg

# Path to feature extractor model 
feature_extractor: triplet_model_param.pt

# Path to classifier model 
classifier: knn_model.sav

# How many of the nearest points are required for the extraction
topn: 10

# Path to file with class names
class_names: classname.txt

#Path to save prediction 
prediction_savefile: data_file.json # or False if not save

