# Path to embedding model parameters 
embedding_model: triplet_model_param.pt

# Path to classifier model parameters 
classifier_model: classifier.pt

# Path to save model parameters 
save_model: trace_pddmodel.pt

num_classes: 20
