
random_seed: 7

cudnn_deterministic: True 

# Number of classes to classify
num_classes: 25

# Path to the archive with data
data_zip_path: 'archive_full.zip'

# Path to the directory to save files
data_save_path: 'data/'

# Fraction of the test dataset
test_size: 0.2

# Number of sample per draw ( to increase probability to
#               contain valid triplets in a batch )
n_sample: 3

batch_size: 12

# Count of epochs:
epochs: 30

# Path to save the plot with embeddings
plot_embeddings_img: './PDD.png'

# Path to save model parameters 
model_save_path: 'triplet_model_param.pt'

# Path to save optimizer parameters
optim_save_path: 'triplet_optim_param.pt'

# Colors of points on plot 
point_colors: ['#00ffff', '#000000', '#0000ff', '#ff00ff',
          '#808080', '#008000', '#00ff00', '#800000',
          '#000080', '#808000', '#800080', '#ff0000',
          '#c0c0c0', '#008080', '#ffff00']

knn_metric: 'cosine'

#optimazer params
lr: 0.0001

weight_decay: 0.00005

#scheduler params

step_size: 7
 
gamma: 0.1
         
